a, b = input().split()
a = int(a)
b = int(b)

print('%d' % 1 if a >= b else 0)
print('%d' % 1 if a > b else 0)
print('%d' % 1 if b >= a else 0)
print('%d' % 1 if b >= a else 0)
print('%d' % 1 if a == b else 0)
print('%d' % 1 if a != b else 0)